#!/bin/sh

case "$1" in
	start)
		printf "Starting wpa_supplicant: "
		/usr/sbin/wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping wpa_supplicant: "
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
