#! /bin/sh



PATH_TO_UDC=/sys/kernel/config/usb_gadget/rockchip/UDC



sleep 1
dev_path=/sys/class/udc
UDC=`ls /sys/class/udc/| awk '{print $1}'`
state=`cat ${dev_path}/${UDC}/state`

if [ "$state"x != "configured"x  ] ; then
	echo ${state}
	echo "yes"
else
	echo ${state}
	echo "no"
fi
